#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

INVOKE_LOG_STDOUT=${INVOKE_LOG_STDOUT:-False}
invoke () {
    if [ $INVOKE_LOG_STDOUT = 'true' ] || [ $INVOKE_LOG_STDOUT = 'True' ]
    then
        /usr/local/bin/invoke $@
    else
        /usr/local/bin/invoke $@ > /usr/src/django/invoke.log 2>&1
    fi
    echo "$@ tasks done"
}

cmd="$@"

echo "-----------------------------------------------------"
echo "STARTING DJANGO ENTRYPOINT $(date)"
echo "-----------------------------------------------------"

# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"


if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"


invoke settingenv
invoke waitfordbs

source $HOME/.bashrc
source $HOME/.override_env

IS_CELERY=${IS_CELERY:-False}
if [ ${IS_CELERY} = "true" ]  || [ ${IS_CELERY} = "True" ]
then
    invoke waitformigrations
    echo "Executing Celery server $cmd"
else

    invoke migrations
    invoke preparefixture

    if [ ${FORCE_REINIT} = "true" ]  || [ ${FORCE_REINIT} = "True" ] || [ ! -e "/mnt/volumes/statics/django_init.lock" ]; then
        invoke loaddata
        invoke updateadmin
        invoke initialized
    fi

    if [ ${APP_ENV} = "production" ]; then
        invoke collectstatic
    fi

    echo "Executing Server $cmd"
fi

echo "-----------------------------------------------------"
echo "FINISHED DJANGO ENTRYPOINT --------------------------"
echo "-----------------------------------------------------"

# Run the CMD
echo "Got command $cmd"
exec $cmd
